# Generated by Django 3.1 on 2020-10-16 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0011_profile_website_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='pinterest_url',
            new_name='linkin_url',
        ),
    ]
