# Generated by Django 3.1 on 2020-10-17 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0012_auto_20201016_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='linkin_url',
            new_name='linkdin_url',
        ),
    ]
